# Generated by Django 3.1 on 2020-08-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardForm',
            new_name='Card',
        ),
    ]
